### ISSUE TITLE
部分图标的轮廓已经被扩展，无法调整描边粗细

### ISSUE THREAD

**Issue by sato94** [bytedance/IconPark#12]
分别是：
钥匙 key
刷新 refresh-one
广告产品 ad-product
录音 voice
摇滚手势 rock-gesture
文件夹 开 folder-open
表格
区域图
地图
电池充电

**Comment by sato94** [comment]
钥匙 key

**Comment by qifengfei** [comment]
收到您的反馈，我会尽快安排优化，谢谢～

**Comment by sato94** [comment]
非常感谢，图标质量非常高，响应还这么及时！

**Comment by AppleMonkey2019** [comment]
已修复，可以尝试最新npm包版本
