### ISSUE TITLE
部分icon文件名大小写与 map.ts 不匹配，导致build失败

### ISSUE THREAD

**Issue by peakcool** [bytedance/IconPark#121]
操作系统: CentOS Linux release 7.7.1908 (Core)
分支: master

执行命令:
```shell
> npm run build:prepare
```

报错信息:

![image](https://user-images.githubusercontent.com/14804014/105122446-2cda2e80-5b11-11eb-9728-78de74c95be3.png)

检查源码，以`vue/icons`为例:

![image](https://user-images.githubusercontent.com/14804014/105122735-bb4eb000-5b11-11eb-9d96-58fa0d52c751.png)

**Comment by peakcool** [comment]
修复

```shell
> cd packages/svg/src/icons
> git mv Addtext.ts AddText.ts
> git mv AddtextTwo.ts AddTextTwo.ts
```

```shell
> cd packages/vue/src/icons
> git mv Addtext.ts AddText.tsx
> git mv AddtextTwo.ts AddTextTwo.tsx
```

```shell
> cd packages/react/src/icons
> git mv Addtext.ts AddText.tsx
> git mv AddtextTwo.ts AddTextTwo.tsx
```

**Comment by peakcool** [comment]
或者可以考虑 读取`icons`下文件，自动生成 `map.ts` 文件

**Comment by AppleMonkey2019** [comment]
非常感谢你的反馈，👍

**Comment by AppleMonkey2019** [comment]
预计本周日修复发版

**Comment by AppleMonkey2019** [comment]
试试【最新NPM包】published:
 - @icon-park/react@1.2.4
 - @icon-park/svg@1.2.4
 - @icon-park/vue-next@1.2.4
- @icon-park/vue@1.2.4
