### ISSUE TITLE
Vue Icon Park 使用文档描述问题

### ISSUE THREAD

**Issue by peakcool** [bytedance/IconPark#128]
环境:

* node@14.15.1
* npm@6.14.8
* vue@2.6.12

按照文档使用
![image](https://user-images.githubusercontent.com/14804014/105317241-f11c9300-5bfc-11eb-9a7a-86cee2b16b47.png)

执行报错
![image](https://user-images.githubusercontent.com/14804014/105316394-c251ed00-5bfb-11eb-8155-960ad8b7fb95.png)

检查发现 `all.ts` 中
```typescript
if (!(type in IconMap)) {
    throw new Error(`${type} is not a valid icon type name`);
}
```

解决方法，`type` 应该为大写，和 `IconType ` 一样
```html
<icon-park type="Home" theme="filled"/>
```

最后建议

* 修改文档为大写写法

或者

* 支持 `x-y` 这样的写法，和 官网图标 name 一致

就我个人而言，我更习惯于第二种

**Comment by AppleMonkey2019** [comment]
的确是，感谢反馈

**Comment by AppleMonkey2019** [comment]
预计本周日修复，发版

**Comment by AppleMonkey2019** [comment]
试试【最新NPM包】published:
 - @icon-park/react@1.2.4
 - @icon-park/svg@1.2.4
 - @icon-park/vue-next@1.2.4
- @icon-park/vue@1.2.4
