### ISSUE TITLE
图标线重叠 搜索关键词： 展开

### ISSUE THREAD

**Issue by imsole** [bytedance/IconPark#132]
如图，需要仔细看，是在看不到，可以调到深色模式下看
![image](https://user-images.githubusercontent.com/3367457/105365028-ccdea780-5c38-11eb-824f-2a5cd7908429.png)

![image](https://user-images.githubusercontent.com/3367457/105364903-a91b6180-5c38-11eb-935f-66e5ab3f2633.png)

**Comment by AppleMonkey2019** [comment]
@qifengfei

**Comment by qifengfei** [comment]
这是因为我要兼顾线性图标和填充后的展示效果的，如果使用透明度效果，建议是对整个图标设置透明度，这样就不会出现你这种情况。
也可以选择不用透明度，直接使用实色。
后面我们也会考虑开放给用户设置透明度参数，方便用户使用！

**Comment by imsole** [comment]
这个问题确实存在，确实是一个问题
这个问题中午不能改
