### ISSUE TITLE
能否提供图标设计规范的指导文档

### ISSUE THREAD

**Issue by zhuangxiaohui** [bytedance/IconPark#140]
部分个性化图标我们要自己设计,能否提供图标设计规范的指导文档,类似这样文档
https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d02248b75&helptype=draw

**Comment by qifengfei** [comment]
![Uploading image.png…]()

我们的有的，还会不断的优化内容部分，可以先参考这个文档https://bytedance.feishu.cn/docs/doccnU0WZ2HEsYBINa9TfgDtAzP?from=from_copylink

**Comment by zhuangxiaohui** [comment]
谢谢，能解决我的大部分的问题了
