### ISSUE TITLE
希望可以提供外链的图标,如下图

### ISSUE THREAD

**Issue by Mamba-working** [bytedance/IconPark#141]
![image](https://user-images.githubusercontent.com/31275940/106250692-f60dc200-624e-11eb-8bf7-9d25578d3737.png)

**Comment by qifengfei** [comment]
![image](https://user-images.githubusercontent.com/24870029/106251835-6b2dc700-6250-11eb-9522-d4af4dfa60c3.png)
我们是有这个图标的，请查找“分享”或者“share”就可以找到结果，同时我会把标签“外链”补充到该图标下。谢谢反馈
