### ISSUE TITLE
没办法通过css改变颜色 能够向iconfont一样增加批量去色功能

### ISSUE THREAD

**Issue by CJH-1996** [bytedance/IconPark#146]

**Comment by AppleMonkey2019** [comment]
可以的，你试试 
`.i-icon {
     color: red;
}`

**Comment by CJH-1996** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/IconPark"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月28日(星期天) 中午1:02
收件人:&nbsp;"bytedance/IconPark"<IconPark@noreply.github.com&gt;;
抄送:&nbsp;"1054535289"<1054535289@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/IconPark] 没办法通过css改变颜色 能够向iconfont一样增加批量去色功能 (#146)





 
可以的，你试试
 .i-icon { color: red; }
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




我是指直接通过svg下载的图标 没办法改色

**Comment by zhangxinmiao-study** [comment]
通过class 改变 color 不生效

**Comment by guguji5** [comment]
@zhangxinmiao-study 解决了不？咋整
