### ISSUE TITLE
 Injection "ICON_CONFIGS" not found 报错，原因未知

### ISSUE THREAD

**Issue by heianxiyi** [bytedance/IconPark#15]
![image](https://user-images.githubusercontent.com/22736955/93588500-15156100-f9de-11ea-8d4c-7c44bb0efc2b.png)

**Comment by heianxiyi** [comment]
[Vue warn]: Injection "ICON_CONFIGS" not found

**Comment by heianxiyi** [comment]
已发现原因，需要定义provide

**Comment by AppleMonkey2019** [comment]
给楼主点赞，确实是个问题，是我还没来得及修
