### ISSUE TITLE
添加Feelgood图标

### ISSUE THREAD

**Issue by chengxiaoDlo** [bytedance/IconPark#155]
需要feelgood的图标，https://sf1-dycdn-tos.pstatp.com/obj/eden-cn/vskeh7vhpenuloj/yuntu/feelgood.svg

**Comment by AppleMonkey2019** [comment]
@qifengfei

**Comment by qifengfei** [comment]
已添加
![image](https://user-images.githubusercontent.com/24870029/108812660-7d4e1b80-75ea-11eb-9386-7d710d32de70.png)

**Comment by qifengfei** [comment]
done！
