### ISSUE TITLE
@icon-park/react and @byte-design/icons do not behave in accordance

### ISSUE THREAD

**Issue by yi-tuan** [bytedance/IconPark#16]
### Version
@byte-design/icons: 0.11.7
@icon-park/react: 1.0.9

### What's the question?
- The `Loading`  icon can't always rotate
- I added style to  the `Return`  icon but does not work

### What is expected?
The `Loading`  icon should always rotate and the `Return`  icon added style can take effect. I don't know if the other ICONS have problems.

![image](https://user-images.githubusercontent.com/32629463/93728956-e6250800-fbf4-11ea-939d-f7240345cc9f.png)

**Comment by AppleMonkey2019** [comment]
如过去沟通，已解决。如果是用外部IconPark，要用configProvider改一下prefix,改成byted
