### ISSUE TITLE
HDMI接口的图标是不是有点不对……

### ISSUE THREAD

**Issue by niujintao** [bytedance/IconPark#160]
![image](https://user-images.githubusercontent.com/53894741/108452386-5e2a5380-72a3-11eb-853a-62b07145e30f.png)
目前的这个图标是类似于鼠标键盘的那种连接插口，HDMI不是偏扁的吗

**Comment by AppleMonkey2019** [comment]
@qifengfei 看看

**Comment by qifengfei** [comment]
有两种呢，一个是扁平的，一个是圆形的。
![image](https://user-images.githubusercontent.com/24870029/108468921-65ad2500-72c2-11eb-90dc-cb0d184693d1.png)
