### ISSUE TITLE
左侧导航栏 点击跳转显示错误

### ISSUE THREAD

**Issue by createskyblue** [bytedance/IconPark#163]
![image](https://user-images.githubusercontent.com/20317561/108699004-b2e9fa80-753f-11eb-845a-9d4350560b00.png)
点击左侧导航栏->符号
图标显示区域为 符号
但是导航栏显示不正确

**Comment by AppleMonkey2019** [comment]
@loveDstyle  帮忙看看

**Comment by loveDstyle** [comment]
应该已经解决了 如果还有问题 欢迎继续反馈。
