### ISSUE TITLE
在vue3中使用ICON_CONFIGS默认值为undefined

### ISSUE THREAD

**Issue by lhlyu** [bytedance/IconPark#167]
代码如下: demo.vue
```vue
<template>
    <div>
        <More></More>
    </div>
</template>

<script lang="ts">
import { More } from '@icon-park/vue-next'

export default {
    components: {
        More
    },
    setup() {
        return {}
    }
}
</script>
```
- 页面报错

![image](https://user-images.githubusercontent.com/41979509/109383336-e1414e80-7920-11eb-8826-0cc31eb2a854.png)

- debugger

![image](https://user-images.githubusercontent.com/41979509/109383289-91fb1e00-7920-11eb-8231-d0049c191a99.png)

**Comment by lhlyu** [comment]
@dewfall123 不确定是不是[vitepress-for-component](https://github.com/dewfall123/vitepress-for-component)导致的问题

**Comment by liuxuanzy** [comment]
你们用的是哪个版本胡图标库，能不能给个可复现的Demo。我用1.3.0版本没有问题。

**Comment by lhlyu** [comment]
> 你们用的是哪个版本胡图标库，能不能给个可复现的Demo。我用1.3.0版本没有问题。

**Comment by AppleMonkey2019** [comment]
hello，同学，这个事情最终解决了吗？

**Comment by lhlyu** [comment]
@liuxuanzy @AppleMonkey2019 
没有解决，我写了一个[demo](https://github.com/lhlyu/temp)
版本是: v1.3.0

**Comment by AppleMonkey2019** [comment]
好嘞，我们尽快看下

**Comment by liuxuanzy** [comment]
我看了一下，是vitepress-for-component的问题，里面的vite配置将vue/runtime-core和vue/runtime-dom打包到了icon-park里面（你可以在node_modules/.vite下找到）但是在其他引用这两个包的地方，又重新通过esm加载了一份，造成了问题。
通过修改：vitepress-for-component/dist/node/server.js 第15行，增加以下代码可以解决
        optimizeDeps:{
            exclude:['@icon-park/vue-next']
        }

以下代码也可以
        optimizeDeps:{
            include:['vue']
        }


所以我判定这大概率是一个vite配置引起的问题。

**Comment by lhlyu** [comment]
> include:['vue']

已验证，谢谢大佬
