### ISSUE TITLE
Injection "ICON_CONFIGS" not found

### ISSUE THREAD

**Issue by thirtyjin** [bytedance/IconPark#168]
![image](https://user-images.githubusercontent.com/3362864/109390490-e0261680-794c-11eb-8fa9-25acb42414a0.png)
[Vue warn]: Injection "ICON_CONFIGS" not found

found in

---> <IconArrowRightUp>

**Comment by AppleMonkey2019** [comment]
重复性反馈，已沟通，关闭

**Comment by AppleMonkey2019** [comment]
#167
