### ISSUE TITLE
360浏览器不支持打开官网，求开发能解决下，辛苦了！！！

### ISSUE THREAD

**Issue by qasim666** [bytedance/IconPark#188]
360安全浏览器在国内打不开官网，很影响使用，求早点解决这个问题

**Comment by loveDstyle** [comment]
好的，我们尽快解决下这个问题 😅

**Comment by loveDstyle** [comment]
> 360安全浏览器在国内打不开官网，很影响使用，求早点解决这个问题

能否提供下更详细的信息呢？比如电脑操作系统、360浏览器版本等等，我在windows 360最新版上没能复现呢😅

**Comment by loveDstyle** [comment]
最近解决了一个由于script中带有ad字样导致的360浏览器拦截问题，推测该issue与此问题一样，先关闭了，如果还有问题欢迎继续反馈

> 360安全浏览器在国内打不开官网，很影响使用，求早点解决这个问题
