### ISSUE TITLE
标签冲突问题

### ISSUE THREAD

**Issue by hujiayuan033** [bytedance/IconPark#218]
当标签的名字和原生标签的名字相同的时候，无法添加组件
例子：
<filter theme="outline" size="18" fill="#9b9b9b" />
import Filter from '@byte-design/vue-icons/icons/Filter';

此时无法添加过滤器组件

**Comment by yoder** [comment]
import的时候可以自定义名称

**Comment by loveDstyle** [comment]
如果有人遇到标签在浏览器中渲染不出来的问题，很有可能是与浏览器中的原生标签 或是 自定义的元素标签名（web component）冲突，这时建议这样使用
![image](https://user-images.githubusercontent.com/18344013/119074966-91a38800-ba22-11eb-8fdf-33ef516fe0cf.png)
