### ISSUE TITLE
希望能把添加的图标添加到“项目”里

### ISSUE THREAD

**Issue by wuwiwo** [bytedance/IconPark#22]
希望能把选择的图标加入到项目里，这样可以知道项目使用了哪些图标。（可以不用存储到云端，可以的话更好）

**Comment by qifengfei** [comment]
我们已经在做「项目管理」功能了，已经进入内部测试阶段了，敬请期待！

**Comment by wuwiwo** [comment]
> 我们已经在做「项目管理」功能了，已经进入内部测试阶段了，敬请期待！

**Comment by wuwiwo** [comment]
> 我们已经在做「项目管理」功能了，已经进入内部测试阶段了，敬请期待！
非常感谢，很期待。
