### ISSUE TITLE
Vue3 引用 `@vue/runtime-dom` 而不是 `vue` 会与 `webpack.externals` 造成冲突

### ISSUE THREAD

**Issue by uioz** [bytedance/IconPark#227]
我不知道为什么要引入 `@vue/runtime-dom` 而不是 vue.

https://github.com/bytedance/IconPark/blob/e2f7e9fbf6bd7f4c8297e8d54413e7f6f7c007b3/packages/vue-next/src/runtime/index.tsx#L6

这样做会让 `webpack` 去处理 `@vue/runtime-dom` 从而引入一份 `vue`.  

如果使用了 `webpack-cdn-plugin` 把 `vue` 通过 CDN 加载 这是基于 `webpack.externals` 实现的
但是引用 `@vue/runtime-dom` 就会让应用程序中存在两份 `vue`.
一份是 `iconPark` 引入 `@vue/runtime-dom` 所依赖的, 另外一份是通过 CDN 加载的.

两者引用的 `vue` 实例不同, 导致错误:
![image](https://user-images.githubusercontent.com/36815772/118106641-62808b80-b410-11eb-96d7-454ffbfa6029.png)

我修改了构建后的代码:
```javascript
import { inject, provide } from 'vue';
```
清除缓存后编译, 然后就一切正常了.

**Comment by uioz** [comment]
而且 `@vue/runtime-core` 在 readme 里面也说了:
>This package is published only for typing and building custom
>renderers. It is NOT meant to be used in applications.

**Comment by loveDstyle** [comment]
@icon-park/vue-next 1.3.6 已修复此问题
