### ISSUE TITLE
项目管理生成的 web components 脚本不够最小化

### ISSUE THREAD

**Issue by fz6m** [bytedance/IconPark#249]
**项目管理里生成的 web component 脚本：**

![image](https://user-images.githubusercontent.com/59400654/122081923-1de27880-ce32-11eb-9322-580df43fb25e.png)

**里面有类似 `styled-components` 生成的 css ，他们占据了巨大的空白，不太友好（两种版本的 js 均有这种问题）：**

![image](https://user-images.githubusercontent.com/59400654/122082193-5eda8d00-ce32-11eb-8b3f-c13d87f5ff73.png)

**如果你正在使用 `styled-components` 等类似的库，请使用其配套的 babel 插件，可以去除空白并压缩最小化。**

**Comment by loveDstyle** [comment]
确实如此，我们会尽快解决这个问题！

**Comment by loveDstyle** [comment]
相关逻辑已经调整，可以通过更新代码链接来看到最新的效果，感谢反馈～
