### ISSUE TITLE
如何正确地配置 babel-plugin-import ？

### ISSUE THREAD

**Issue by Chinesee** [bytedance/IconPark#25]
在我的`babel.config.js`中，我的配置如下：
```js
plugins = [
  [
    'import',
    {
      libraryName: 'ant-design-vue',
      libraryDirectory: 'es',
      style: true,
    },
    'ant-design-vue',
  ],
  [
    'import',
    {
      libraryName: '@icon-park/vue',
      libraryDirectory: 'es/icons',
      camel2DashComponentName: false,
    },
    '@icon-park/vue',
  ],
]
```
这样配置的话，就会导致`import { DEFAULT_ICON_CONFIGS } from '@icon-park/vue'`报错：DEFAULT_ICON_CONFIGS is not defined
在我查看了库目录之后，发现`DEFAULT_ICON_CONFIGS`的导出文件不在`es/icons`下，我猜测是没有正确配置`libraryDirectory`的原因导致报错，所以应该如何正确配置呢？期待解答~

**Comment by liuxuanzy** [comment]
Try `import { DEFAULT_ICON_CONFIGS } from '@icon-park/vue/es/runtime'` instead. 

Maybe we need to write a new plug-in to meet this requirement

**Comment by Chinesee** [comment]
@liuxuanzy 
It works . Thanks.

**Comment by AppleMonkey2019** [comment]
Try @icon-park/vue@1.1.5
