### ISSUE TITLE
icon项目管理中用到的id不适合管理，使用过程中可读性比较差，建议尽快上线自定义命名type的功能

### ISSUE THREAD

**Issue by michael8512** [bytedance/IconPark#251]

**Comment by loveDstyle** [comment]
我们有意识到这个问题，方案还在设计中，主要考虑保证自定义命名的唯一性 以及 已经被引用的图标（以自定义标识方式）在它的标识被改变时的提示（就如这个issue中提到的 https://github.com/bytedance/IconPark/issues/250#issue-922036879），如果没有这个提示，用户在更换代码链接如果不一并更新图标代码，会出现无法正确显示图标的问题

**Comment by loveDstyle** [comment]
目前已支持以name方式使用图标，欢迎试用&反馈
