### ISSUE TITLE
Vue 或者 React 有提供统一配置的方式吗

### ISSUE THREAD

**Issue by lin-mt** [bytedance/IconPark#275]
类似全局配置，然后引用的时候默认使用全局配置，具体引用的配置可以覆盖全局配置

**Comment by loveDstyle** [comment]
https://www.npmjs.com/package/@icon-park/vue 文档中的 Global Config 部分
![image](https://user-images.githubusercontent.com/18344013/125551106-11cb55b3-9907-4fc8-b112-df4529667f70.png)
