### ISSUE TITLE
使用项目管理的方式，引用了两个icon的链接后其中一个无法获取到

### ISSUE THREAD

**Issue by michael8512** [bytedance/IconPark#276]
<script src="https://sf1-hscdn-tos.pstatp.com/obj/iconpark/icons_1776_2.93a284011626ff05b7428f3cd75b7a26.es5.js" ></script>
    <script src="https://sf3-hscdn-tos.pstatp.com/obj/iconpark/icons_1185_2.5987d5cbb5d7eb27dacdf03e301ca243.es5.js"></script>

![Lark20210714-163443](https://user-images.githubusercontent.com/30284157/125590826-d132b356-d0c1-4345-a679-8010d6a71429.png)

**Comment by loveDstyle** [comment]
这个应该是当时网络/cdn问题，现在应该ok了？

**Comment by loveDstyle** [comment]
closed due to inactivity
