### ISSUE TITLE
Website: lighter and faster color picker component

### ISSUE THREAD

**Issue by omgovich** [bytedance/IconPark#28]
Hi! Nice icons and website!

I noticed that you're using `react-color` on your website.
Just want to suggest you consider using a lighter and faster option since `react-color` is 140 KB (far larger than the entirety of react-dom), is not tree-shakeable, is not accessible, does not support keyboard navigation, pulls in 11 dependencies, and is not as fast as it could be. See https://bundlephobia.com/result?p=react-color@2.18.1

Several months ago I created `react-colorful` as a modern replacement for `react-color`. My library is 18 times lighter (less than 2 KB gzip) and way faster:
- [Demo](https://omgovich.github.io/react-colorful/)
- [Docs](https://github.com/omgovich/react-colorful)
- [Benchmarks](https://github.com/omgovich/react-colorful#why-react-colorful)
- [Article on DEV.to](https://dev.to/omgovich/react-colorful-1-8-kb-color-picker-for-react-fast-dependency-free-customizable-and-accessible-8le)

Let me know if you're interested in using my component or if you need any help with migration.

Regards,
Vlad

**Comment by AppleMonkey2019** [comment]
Wow, a nice component. Thanks for your suggestion.
