### ISSUE TITLE
项目图标下载问题

### ISSUE THREAD

**Issue by yuqiuzh** [bytedance/IconPark#282]
1. 配置了英文名称，按中文名称下载
2. 中文名字修改成了英文，下载的文件名添加了一串数字

项目批量下载根本没法用，批量下载下来还要全部重命名才能用

**Comment by loveDstyle** [comment]
之前文件名拼接的数字是为了防止图标命名冲突的情况加上的；
针对反馈的问题，我们刚才调整了下载方式，可以刷新再试下看是不是期望的效果～

**Comment by yuqiuzh** [comment]
好了，thank you
