### ISSUE TITLE
BUG - 提示找不到模块 IconPark

### ISSUE THREAD

**Issue by zxbe** [bytedance/IconPark#31]
项目：vue3 - vite - TS
错误描述：import {IconPark} from '@icon-park/vue-next/all'; 提示找不到模块 IconPark

**Comment by AppleMonkey2019** [comment]
这个是vite的问题，可以参考一下控制台的提升，添加一下vite的配置

**Comment by zxbe** [comment]
> 控制台的提升

具体指的是啥，有链接吗？小白一枚，望谅解

**Comment by safagwq** [comment]
> > 控制台的提升
> 
> 具体指的是啥，有链接吗？小白一枚，望谅解

写成这样就可以了  import { IconPark } from '@icon-park/vue/es/all';

**Comment by AppleMonkey2019** [comment]
感谢反馈，README里描述有误，已修复
