### ISSUE TITLE
关于下载使用默认名

### ISSUE THREAD

**Issue by Clearlove7NB** [bytedance/IconPark#32]
现在下载下来的名称默认是英文，对于我这种英文不好的来说，常见的还可以翻译，大部分都不认识，下载的一多，就分不清谁是谁了，建议让下载下来的默认名称含有中文，或者说支持中英文切换，可以选择中文下载还是英文下载。

![微信截图_20201023175710](https://user-images.githubusercontent.com/73338962/96990149-4cd17480-1559-11eb-9ccf-8e93c9b7e290.png)

**Comment by loveDstyle** [comment]
此功能已经上线啦！现在下载图片时的文件名会跟随当前网站的语言来，欢迎试用反馈

**Comment by qifengfei** [comment]
done！
