### ISSUE TITLE
项目管理—>创建项目时，提交按钮貌似未做防抖处理，导致创建多个重名项目

### ISSUE THREAD

**Issue by Variable-1760** [bytedance/IconPark#341]
![新建项目请求未处理防抖操作](https://user-images.githubusercontent.com/89447429/133381092-8890080d-6f71-4e73-9ba5-bdd763239bcb.png)
![结果：创建两个重名项目](https://user-images.githubusercontent.com/89447429/133381272-623e5aa0-7eb6-4860-9777-b1f177b4a6ad.png)

**Comment by loveDstyle** [comment]
了解，后续处理下这块😅

**Comment by loveDstyle** [comment]
fixed
