### ISSUE TITLE
自建的项目，无法复制SVG到AI里，只能下载。

### ISSUE THREAD

**Issue by lilululi** [bytedance/IconPark#368]

**Comment by loveDstyle** [comment]
是说点复制svg没反应？ 用的什么浏览器

**Comment by lilululi** [comment]
点击复制SVG有反应，网页上显示复制成功了，但是在AI或者XD里面粘贴不出来。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/IconPark"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月23日(星期二) 下午5:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytedance/IconPark] 自建的项目，无法复制SVG到AI里，只能下载。 (Issue #368)





 
是说点复制svg没反应？ 用的什么浏览器
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lilululi** [comment]
> 是说点复制svg没有反应？用什么浏览器

360跟谷歌浏览器都没反应。

**Comment by loveDstyle** [comment]
针对此问题做了调整，刷新页面再试下？

**Comment by lilululi** [comment]
> 针对此问题做了调整，刷新页面再试下？

好了，谢谢！
