### ISSUE TITLE
如何按照后端下发的图标名称, 进行按需加载

### ISSUE THREAD

**Issue by zhangrunhao** [bytedance/IconPark#375]
情景: 
1. 图标名称存储在数据库
2. 前端根据后端下发的图标名称进行展示

当前实现方式:
1. 引入全部图标, "@icon-park/react/es/all"
2. 使用 type参数进行展示  `<Icon type={图标名称}></Icon>`

当前问题:
1. 全部加载图标,  造成包体积过大

尝试方法和遇到的问题:
1. 下载所有svg, 使用img的src进行展示, 问题: 无法改变颜色
2. 懒加载无法根据服务器下载的图标名称, 进行展示

希望达成:
1. 后端下发图标名称
2. 前端根据图标名称加载图标
3. 前端可根据情况, 改变图标颜色.

感谢大佬解答.

**Comment by loveDstyle** [comment]
你描述的情况在技术上是不可行的：理论上后端可以下发全量图标名称中的任何一个（甚至下发错误的名称），前端为了在运行时能正常显示，代码中必须将全量图标打包。

类似webpack的动态打包也是将特定文件夹下的所有文件进行打包

**Comment by zhangrunhao** [comment]
> 你描述的情况在技术上是不可行的：理论上后端可以下发全量图标名称中的任何一个（甚至下发错误的名称），前端为了在运行时能正常显示，代码中必须将全量图标打包。
> 
> 类似webpack的动态打包也是将特定文件夹下的所有文件进行打包

这样的话, 前端打包后的体积会变得非常大. 有没有好的解决方案?

**Comment by loveDstyle** [comment]
你这种场景，考虑下后端直接下发svg串吧，可以通过 svg 包实现 https://www.npmjs.com/package/@icon-park/svg

**Comment by zhangrunhao** [comment]
非常感谢解答, 目前我们讨论的结果, 这也是最折中的一个解决方法.
