### ISSUE TITLE
不能设置填充为currentColor，无法使用

### ISSUE THREAD

**Issue by gxlinhai** [bytedance/IconPark#39]
currentColor，只为继承父级颜色，你不让设置，这怎么搞？

**Comment by loveDstyle** [comment]
是说网站上不支持吗😅？代码上是支持的哈

![image](https://user-images.githubusercontent.com/18344013/97416341-44a27c00-1941-11eb-83bf-1638ef20fb8e.png)

合法color值应该都ok

**Comment by liuxuanzy** [comment]
默认情况下，颜色就是currentColor，你拿到的根组件是一个span而不是svg。使用fill: currentColor没有效果，如果要通过CSS继承样式，可以使用
``` color: inherit; ``` 或者 ```color: currentColor;```来实现。请不要尝试给组件增加fill属性
