### ISSUE TITLE
iconPark官方图标库可以免费商用吗？

### ISSUE THREAD

**Issue by wawu123481** [bytedance/IconPark#402]
只看到说可以免费使用

**Comment by wawu123481** [comment]
企业可以免费商用不？

**Comment by loveDstyle** [comment]
详见 https://bytedance.feishu.cn/wiki/wikcn3mntCdchXbMgJFll98Ytnb

**Comment by wawu123481** [comment]
> 详见 https://bytedance.feishu.cn/wiki/wikcn3mntCdchXbMgJFll98Ytnb

这个倒是看到了，只说了免费使用，没说企业商用怎么授权

**Comment by wawu123481** [comment]
> 详见 https://bytedance.feishu.cn/wiki/wikcn3mntCdchXbMgJFll98Ytnb

看到那个授权协议了，还是有点没懂。企业要商用的话，需要做什么呢。请大佬解答一下

**Comment by loveDstyle** [comment]
建议参考对采用 apache-2.0 开源协议的一般作品的处理方式，尊重版权、商标，分发时保留归属声明。详细处理方式请咨询专业法律人士

**Comment by WuJiY** [comment]
需要保留归属声明 ，可免费商用
