### ISSUE TITLE
iconpark-icon标签上为什么会自动追加一个name属性?

### ISSUE THREAD

**Issue by Soo-For** [bytedance/IconPark#405]
![image](https://user-images.githubusercontent.com/66558137/152915547-b1d9ec4c-29f9-40b2-b4f2-60b907f615b2.png)
服务端渲染时，自动追加的name属性导致在ie11下报错了。

**Comment by loveDstyle** [comment]
name 是用来表示 该显示哪个图标的，截图看到只是 warning， 实际渲染结果如何？

**Comment by Soo-For** [comment]
> name 是用来表示 该显示哪个图标的，截图看到只是 warning， 实际渲染结果如何？

可以正常渲染。

建议在没有设置name的情况下还是不要添加这个属性。项目里接入了js错误监控，该报错信息会被上报。

![image](https://user-images.githubusercontent.com/66558137/152924901-3f711ab2-c4c7-40e0-8dec-62771e4e7c54.png)

**Comment by Soo-For** [comment]
找到解决方案了：
iconpark-icon标签中，name也加上icon-id相同字段即可解决ie11中报错。
