### ISSUE TITLE
”官方图标库“页面BUG

### ISSUE THREAD

**Issue by Jimmyzm** [bytedance/IconPark#41]
- 右侧工具栏刷新后错位
- 左侧导航栏定位高亮不准确

环境：
win10
Chrome (86.0) & Edge (86.0)

**Comment by Jimmyzm** [comment]
![image](https://user-images.githubusercontent.com/26268346/97547823-4172c300-1a09-11eb-9d65-ec266fef4dc0.png)
补张图~

**Comment by loveDstyle** [comment]
感谢反馈，滚动问题现在应该解决了，有空可以试试
