### ISSUE TITLE
VUE项目中使用，图标不显示

### ISSUE THREAD

**Issue by mforgithub** [bytedance/IconPark#429]
问题如标题，使用的是yarn管理项目包，然后根据文档的这一段描述，操作过后，编译也不报错，页面显示也正常，就是一直显示宽度是0，下图是我参照的文档截图
![图片](https://user-images.githubusercontent.com/29246850/159763515-3b24deb1-e29e-49af-811e-a042354cae48.png)
测试的代码如下：
![图片](https://user-images.githubusercontent.com/29246850/159763650-a1483a19-0471-4006-901f-e1bf9d045b15.png)
然后引用的代码如下：
![图片](https://user-images.githubusercontent.com/29246850/159763728-dced1bb2-0585-488a-932c-ed0a151bf1c6.png)
在main.js中也引用了样式文件：
![图片](https://user-images.githubusercontent.com/29246850/159763835-2d096569-1d97-47fd-ac0b-4c27aa762188.png)
最终浏览的效果如下：
![图片](https://user-images.githubusercontent.com/29246850/159764009-61629e05-bb6e-49a3-9e09-6c3630550084.png)
然后<bookmark标签本来从官网上复制的时候，没有book和mark中间的横岗，也试过没有横岗的代码了，结果还是一样，不知道问题出在哪里
最后附上我项目的yarn文件
[yarn.zip](https://github.com/bytedance/IconPark/files/8335381/yarn.zip)

**Comment by loveDstyle** [comment]
vue 写的少，不是 这样吗？
```
components: { 
 Bookmark 
}
```

**Comment by mforgithub** [comment]
> vue 写的少，不是 这样吗？
> 
> ```
> components: { 
>  Bookmark 
> }
> ```

哦哦，还真是，不好意思，犯了低级错误 -_-||
