### ISSUE TITLE
所有图标都有底色，没有线性图标，请设计一个退件管理，谢谢！！！！

### ISSUE THREAD

**Issue by dimeiis** [bytedance/IconPark#43]

**Comment by qifengfei** [comment]
下次迭代就会把线性风格的底色去掉了，现在还在优化中，敬请期待！

**Comment by dimeiis** [comment]
坐等！！谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytedance/IconPark"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 上午10:46
收件人:&nbsp;"bytedance/IconPark"<IconPark@noreply.github.com&gt;;
抄送:&nbsp;"Chloe"<250203220@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bytedance/IconPark] 所有图标都有底色，没有线性图标，请设计一个退件管理，谢谢！！！！ (#43)





 
下次迭代就会把线性风格的底色去掉了，现在还在优化中，敬请期待！

**Comment by loveDstyle** [comment]
感谢反馈，现在应该已经解决啦，有空可以试试
