### ISSUE TITLE
希望增加原生js的应用场景，html标签直接放cdn就可

### ISSUE THREAD

**Issue by XindiShang** [bytedance/IconPark#430]
辛苦~~

**Comment by loveDstyle** [comment]
看看这种 https://bytedance.feishu.cn/wiki/wikcnQV4micaPYg5VsQAoEpEE6b

**Comment by XindiShang** [comment]
> 看看这种 https://bytedance.feishu.cn/wiki/wikcnQV4micaPYg5VsQAoEpEE6b

谢谢铁子
