### ISSUE TITLE
Size of `text-bold` icon

### ISSUE THREAD

**Issue by pd4d10** [bytedance/IconPark#6]
We are trying to use it in [ByteMD](https://github.com/bytedance/bytemd)

It seems the size of `text-bold` is slightly different from other icons if we put them together (16x16):

![image](https://user-images.githubusercontent.com/9524411/91977504-5a3a6180-ed55-11ea-8998-08cdda9fc3eb.png)

**Comment by AppleMonkey2019** [comment]
设计师同学看一下哈

**Comment by qifengfei** [comment]
我们就需要这7个图标吗？如果还有其他的图标应用场景，可以统一一块看这个问题，我们可以提供一套定制的图标。

**Comment by AppleMonkey2019** [comment]
@qifengfei 这个是不是在2012个图标时候已解决？

**Comment by qifengfei** [comment]
done！
