### ISSUE TITLE
Is @icon-park/compiler source code publicly available?

### ISSUE THREAD

**Issue by kokjinsam** [bytedance/IconPark#632]
Hello, I'm looking to port this lib to Elixir. Right now, I'm only able to generate line-themed icons. The missing piece is the compiler that transforms and configures the SVG icons. It would be greatly appreciated if the compiler is available publicly.

**Comment by lhlyu** [comment]
[链接](https://github.com/icon-space/IconSpace/tree/main/packages/compiler)

**Comment by kokjinsam** [comment]
Thank you.
