### ISSUE TITLE
react的className属性不生效

### ISSUE THREAD

**Issue by wsz7777** [bytedance/IconPark#65]
![image](https://user-images.githubusercontent.com/33828341/102779467-3ddb3700-43cf-11eb-8447-15b7386465fd.png)
![image](https://user-images.githubusercontent.com/33828341/102779491-47fd3580-43cf-11eb-8285-ded93ed9c6d2.png)

**Comment by AppleMonkey2019** [comment]
试试1.1.4版本

**Comment by wsz7777** [comment]
现在好了，我还看了看那个文件，看到有className，我还以为是你们没有重编译就发包了
