### ISSUE TITLE
【需求】新增一个 Ai/Chat robot/open ai 方面的图标

### ISSUE THREAD

**Issue by DylanZella** [bytedance/IconPark#682]
这个图标应该应用场景还是比较广的，麻烦维护者有时间加一下。谢谢！

**Comment by lhlyu** [comment]
![image](https://user-images.githubusercontent.com/41979509/227945565-5f9d163d-d60e-4c26-98d9-f4e82ec71d6b.png)
[链接](https://icon-space.github.io/doc/)

**Comment by DylanZella** [comment]
> ![image](https://user-images.githubusercontent.com/41979509/227945565-5f9d163d-d60e-4c26-98d9-f4e82ec71d6b.png) [链接](https://icon-space.github.io/doc/)

谢谢
