### ISSUE TITLE
建议可以通过单一组件传入props引用不同图标，或者打包成图标字体用classname引用

### ISSUE THREAD

**Issue by wkcole** [bytedance/IconPark#71]
一个图标一个组件很容易命名冲突。。。

**Comment by AppleMonkey2019** [comment]
你说的是打包全量图标，通过传递图标名字区分不同图标的方式吗？<Icon type=${iconName} />

**Comment by liuxuanzy** [comment]
命名冲突建议使用ES6 Import来解决，例如import {People as IconPeople} from '@icon-park/icons'，另外图标库都提供了通过props引用图标的功能，具体可以参考
https://github.com/bytedance/IconPark/tree/master/packages/react#icon-component
https://github.com/bytedance/IconPark/tree/master/packages/vue#icon-component
