### ISSUE TITLE
使用版权问题

### ISSUE THREAD

**Issue by zwb2012** [bytedance/IconPark#712]
您好，图标使用标注是免费使用。但是没有标注是否可用用于商业用途。请问是否可以商用？如果可以商用，希网可以在官网显示进行版权商用说明。这样用起来放心

**Comment by lhlyu** [comment]
可以查看项目的开源协议[Apache License 2.0](https://github.com/bytedance/IconPark/blob/master/LICENSE)

下面列表都是支持的：

- [x] 商业用途
- [x] 修改
- [x] 分配
- [x] 专利使用
- [x] 私人使用

**Comment by zwb2012** [comment]
感谢
