### ISSUE TITLE
Vue.install报错

### ISSUE THREAD

**Issue by wkcole** [bytedance/IconPark#75]
https://github.com/bytedance/IconPark/blob/master/packages/vue/README.md#install

Vue全局安装文档中
![image](https://user-images.githubusercontent.com/8675871/103076768-736b6480-4609-11eb-88c9-87af562775ec.png)
Vue实例好像没有install函数?

**Comment by wkcole** [comment]
终于全局安装完了，文档坑挺多

一我盲猜是Vue.comonent不是Vue.install  
二是@icon-park/vue 导出了图标和一个默认配置，Vue.component的时候需要注意下  
三是图标导出的组件名并不是图标名，而是 icon+图标名，比如说`<icon-home />`
```js
Object.values(icons).forEach(icon => {
  icon.name && Vue.component(icon.name, icon)
})
```

**Comment by wkcole** [comment]
建议吧，可以用 Vue.use 全局安装。。。。

**Comment by wkcole** [comment]
https://github.com/ElemeFE/element/blob/dev/src/index.js

参考一下这里，提供一下install函数就行了 = =

**Comment by AppleMonkey2019** [comment]
感谢反馈，可以提一个PR\(^o^)/~

**Comment by wkcole** [comment]
最近比较忙，周末我看看

**Comment by AppleMonkey2019** [comment]
试试@icon-park/vue@1.1.5，这里补充了例子：https://github.com/IconPark/demos/blob/master/vue2-icon-demos/src/App.vue
