### ISSUE TITLE
希望也能提供下游戏手柄及手柄按钮相关的图标

### ISSUE THREAD

**Issue by jx3fans** [bytedance/IconPark#77]
可以考虑使用“游戏手柄”分类
手柄分为 XBOX手柄、PS手柄等，可以分别绘制对应的图标。
按钮方面，xbox手柄有 A、B、X、Y、LB、RB、LT、RT、LS、RS、START、BACK、以及上下左右方向键、外加西瓜键。
PS手柄方面就不太了解了，我记得有X、O、方块、三角这些。

希望开发组也能针对这些绘制一些图标。谢谢。
![2d9449d0-49aa-405f-828e-18b058825280](https://user-images.githubusercontent.com/870076/103137338-1653d980-4703-11eb-8c0b-4809edf0170b.jpg)
![QQ截图20201225224823](https://user-images.githubusercontent.com/870076/103137368-51eea380-4703-11eb-943c-b85d2bf98419.png)

**Comment by qifengfei** [comment]
done！
