### ISSUE TITLE
[BUG] 在electron-vue中按需引入IconPark, 切换到使用IconPark的页面时报如下错误

### ISSUE THREAD

**Issue by 1273082756** [bytedance/IconPark#80]
`[Vue warn]: Injection "ICON_CONFIGS" not found

found in

---> <IconIdCardH>
       <Setting> at src/renderer/pages/setting.vue
         <VoiceNative> at src/renderer/App.vue
           <Root>`

**Comment by AppleMonkey2019** [comment]
感谢反馈，我跟进一下

**Comment by AppleMonkey2019** [comment]
试试 @icon-park/vue@1.1.5，补充了例子：https://github.com/IconPark/demos
