### ISSUE TITLE
生成代码在线链接失败

### ISSUE THREAD

**Issue by XiaoChengji** [bytedance/IconPark#886]
你好，生成代码在线链接失败，整体请求如下：

curl 'https://iconpark.oceanengine.com/api/group/generate-script' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: zh-CN,zh;q=0.9,zh-TW;q=0.8,en;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json;charset=UTF-8' \
  -H 'cookie: MONITOR_WEB_ID=89f4616d-c4b0-4ffc-a7f2-faf4b2400436; s_v_web_id=verify_m197hb6v_w6T9nUZz_OD7U_4Yba_Ba8B_GGSraCYc2mM3; passport_csrf_token=6481235dd19395387404b2481599ce57; passport_csrf_token_default=6481235dd19395387404b2481599ce57; odin_tt=798a17cfe7a911ee659c9168e28dce29dcec10bbf05020776a2db2083fb02cf1221bb3186fe5abd6eae79d2f61effd1203d9c85cfb0cc2721b4fa26986ab2946; is_staff_user_okee=false; store-region=cn-gd; store-region-src=uid; passport_csrf_token_wap_state=2003cfec3gAToVCgoVPZIDExNjQzYjMyODI4NzE2ZWYxYzJkNzdlNzE3Njc5YmUzoU7ZIGh0dHBzOi8vaWNvbnBhcmsub2NlYW5lbmdpbmUuY29toVYBoUkAoUQAoUHRDRuhTQChSLhpY29ucGFyay5vY2VhbmVuZ2luZS5jb22hUgKiUEzRBbCmQUNUSU9OoKFM2SVodHRwczovL2ljb25wYXJrLm9jZWFuZW5naW5lLmNvbS9ob21loVTZIGQ0Yjk3MjNmOWQzNDNkNjhhMmJlYWQ4MmI5MDE2MTVmoVcAoUYAolNBAKFVwqJNTMI%253D; n_mh_okee=memb1xbV4j0nBGIcI1kLQKi4HlzOjW9OYG8w8LIvQnk; passport_auth_status_okee=63bd6afca34cc02e6a386be7ecaaac5d%2C; passport_auth_status_ss_okee=63bd6afca34cc02e6a386be7ecaaac5d%2C; sid_guard_okee=a983167eb434324973abb13604be57dd%7C1726749688%7C5184000%7CMon%2C+18-Nov-2024+12%3A41%3A28+GMT; uid_tt_okee=bae67d1760c69c5ed95eb2034f790e21; uid_tt_ss_okee=bae67d1760c69c5ed95eb2034f790e21; sid_tt_okee=a983167eb434324973abb13604be57dd; sessionid_okee=a983167eb434324973abb13604be57dd; sessionid_ss_okee=a983167eb434324973abb13604be57dd; sid_ucp_v1_okee=1.0.0-KGZmZjdiNzMyZmZlNDUzMmRiZTVmZTc1MWQ3ODkyMmQxOTU4ZmM3M2MKFwiX5eDSu439AxD4t7C3BhibGjgCQPEHGgJsZiIgYTk4MzE2N2ViNDM0MzI0OTczYWJiMTM2MDRiZTU3ZGQ; ssid_ucp_v1_okee=1.0.0-KGZmZjdiNzMyZmZlNDUzMmRiZTVmZTc1MWQ3ODkyMmQxOTU4ZmM3M2MKFwiX5eDSu439AxD4t7C3BhibGjgCQPEHGgJsZiIgYTk4MzE2N2ViNDM0MzI0OTczYWJiMTM2MDRiZTU3ZGQ; _gid=GA1.2.1433152378.1726749953; _ga_L06HKX6C3X=GS1.1.1726749254.2.1.1726749953.0.0.0; _ga=GA1.1.194338461.1726745153' \
  -H 'origin: https://iconpark.oceanengine.com' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://iconpark.oceanengine.com/projects/35369/detail' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'x-secsdk-csrf-token: DOWNGRADE' \
  --data-raw '{"groupID":35369}'

**Comment by XiaoChengji** [comment]
接口错误提示如下：

{
    "data": {},
    "code": 1,
    "msg": "can't upload file to TOS: icons_35369_1.2106d9830433077cf80952d0ffbe6d93.js, statusCode: 403, body: {\"Success\":-1,\"error\":{\"code\":4006,\"message\":\"auth failed, please check the access key\"}}, x-tos-request-id: 947c28ec1e68dcaf66ec1e68-ad37033"
}

**Comment by yy523301** [comment]
can't upload file to TOS: svg_35372_29.e93aac0523c8c08935bc38b0f96cf4c2.js, statusCode: 403, body: {"Success":-1,"error":{"code":4006,"message":"auth failed, please check the access key"}}, x-tos-request-id: f9f82bec51049ce066ec5104-a993a11   我也一样

**Comment by Tianwu** [comment]
同样的问题

**Comment by panghaojie** [comment]
can't upload file to TOS: icons_11168_245.5d3cba78dda5d9d809b6c04bfd160e42.js, statusCode: 403, body: {"Success":-1,"error":{"code":4006,"message":"auth failed, please check the access key"}}, x-tos-request-id: cebff5ece07532ce66ece075-ad25c94

**Comment by hzpenny** [comment]
一样的问题啊，服务器出问题了吗

can't upload file to TOS: icons_17275_472.f8fe37e6201e20774fd969f2ff60aea6.es5.js, statusCode: 403, body: {"Success":-1,"error":{"code":4006,"message":"auth failed, please check the access key"}}, x-tos-request-id: f9f82bece58b14a366ece58b-a993a11

**Comment by slightc** [comment]
still error @AppleMonkey2019

**Comment by ZWenJiu** [comment]
也遇到了同样的问题

**Comment by liu-huangshu** [comment]
an't upload file to TOS: icons_25453_380.3e10f4e9aa72107a491553f44d4c14c0.es5.js, statusCode: 403, body: {"Success":-1,"error":{"code":4006,"message":"auth failed, please check the access key"}}, x-tos-request-id: dd3fbef0d1af95ce66f0d1af-ac63d5d

重新退出登录也不行哦，项目组织里所有成员也不行哦

**Comment by XiaoChengji** [comment]
图标生成在线链接功能已恢复正常，关闭该issue了！！！
